# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xmlbuilder_create <- function(use_prolog = TRUE) {
    .Call(`_xmlwriter_xmlbuilder_create`, use_prolog)
}

xmlbuilder_to_string <- function(xb) {
    .Call(`_xmlwriter_xmlbuilder_to_string`, xb)
}

xmlbuilder_start_element <- function(xb, tag, att) {
    invisible(.Call(`_xmlwriter_xmlbuilder_start_element`, xb, tag, att))
}

xmlbuilder_write_raw_xml <- function(xb, raw_xml) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_raw_xml`, xb, raw_xml))
}

xmlbuilder_write_element <- function(xb, tag, text, att) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_element`, xb, tag, text, att))
}

xmlbuilder_end_element <- function(xb, tag) {
    invisible(.Call(`_xmlwriter_xmlbuilder_end_element`, xb, tag))
}

xmlbuilder_text_node <- function(xb, text) {
    invisible(.Call(`_xmlwriter_xmlbuilder_text_node`, xb, text))
}

xmlbuilder_write_comment <- function(xb, comment) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_comment`, xb, comment))
}

xmlbuilder_write_cdata <- function(xb, cdata) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_cdata`, xb, cdata))
}

xmlbuilder_write_doctype <- function(xb, doctype) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_doctype`, xb, doctype))
}

xmlbuilder_write_processing_instruction <- function(xb, target, pi) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_processing_instruction`, xb, target, pi))
}

xmlbuilder_write_dataframe <- function(xb, df, row_tag = "row", dataframe_tag = NULL) {
    invisible(.Call(`_xmlwriter_xmlbuilder_write_dataframe`, xb, df, row_tag, dataframe_tag))
}

dataframe_xml_list <- function(df, row_tag) {
    .Call(`_xmlwriter_dataframe_xml_list`, df, row_tag)
}

rcpp_list_to_xml_string <- function(xml) {
    .Call(`_xmlwriter_list_to_xml_string`, xml)
}

